### ISSUE TITLE
make it clear how to upload a structure

### ISSUE THREAD

**Issue by ltalirz** [yakutovicha/mc-epfl-lsmo#2]
once we are at a stage where you want to give this as a turnkey solution to an experimentalist, it needs to be clear how to upload a structure (either do it directly in the app or link to a structure importer).

Not that urgent for the moment.

**Comment by yakutovicha** [comment]
as we now have the famous [aiidalab-widgets-base](https://github.com/aiidalab/aiidalab-widgets-base) package, it should be fixed once we upload the structure using StructureUploadWidget class.

**Comment by yakutovicha** [comment]
it is all super clear now :)
